export const MERCHANT_FEED_HEADERS = [
  'shopName',
  'shopDomain',
  'productTitle',
  'brand',
  'model',
  'variantName',
  'storageGb',
  'ramGb',
  'color',
  'ean',
  'gtin',
  'mpn',
  'condition',
  'price',
  'shippingCost',
  'currency',
  'deliveryMinDays',
  'deliveryMaxDays',
  'stockStatus',
  'paymentMethods',
  'returnDays',
  'returnShipping',
  'warrantyMonths',
  'productRating',
  'productReviewCount',
  'storeRating',
  'storeReviewCount',
  'productUrl',
  'imageUrl',
  'description',
] as const;

export const MERCHANT_FEED_TEMPLATE = `${MERCHANT_FEED_HEADERS.join(',')}\n`;
